### ISSUE TITLE
python3 compatible?

### ISSUE THREAD

**Issue by bbrendon** [rory/apache-log-parser#18]
```
Traceback (most recent call last):
  File "log.py", line 29, in <module>
    log_line_data = line_parser(loop) #We are using the apache parser as specified above
  File "/usr/local/lib/python3.4/dist-packages/apache_log_parser/__init__.py", line 246, in parse
    match = self.log_line_regex.match(log_line)
TypeError: can't use a string pattern on a bytes-like object

```

**Comment by amandasaurus** [comment]
Hi, I initially designed this with python2 in mind, I don't think i've tried it with py3. It would be nice to have py3 compatibility, but I have no time to work on this now. Patches welcome!

**Comment by scottwilliambeasley** [comment]
Love your module. Patch submitted!
